[package]
name = "loitsu-editor"
version = "0.4.0"
edition = "2021"
authors = ["Amos Peltonen"]

[dependencies]
loitsu = { path = "../loitsu", features = ["editor"] }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.39"
serde_json = "1.0.108"
serde = "1.0"

[profile.release]
lto = true
