[package]
name = "loitsu-asset-gen"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
image = "0.24"
serde_json = "1.0"
serde = "1.0"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
loitsu = { path = "../loitsu" }
bitcode = "0.5.1"
