[package]
name = "loitsu-asset-gen"
version = "0.4.0"
edition = "2021"
authors = ["Amos Peltonen"]

[dependencies]
image = "0.24"
serde_json = "1.0"
serde = "1.0"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
loitsu = { path = "../loitsu" }
bitcode = "0.5.1"
