[package]
name = "loitsu-asset-gen"
version = "0.1.0"
edition = "2021"
authors = ["Amos Peltonen"]

[dependencies]
image = "0.24.7"
serde_json = "1.0.108"
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
