[package]
name = "loitsu-asset-gen"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
loitsu = { path = "../loitsu" }
image.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
bitcode.workspace = true
